name: مناهج

title: مناهج للحلول

description: موقع مناهج التعليمي لحل الكتب الدراسية عبر منصة تعليمية ينشر الموقع من خلال انشاء فصول دراسية للمرحلة الابتدائية والمتوسطة والثانوية يساهم الموقع في نشر التعليم عبر نشر الكتب الدراسية

author:
  name: مناهج للحول™
  uri: //elzahaby.tk
  
lang: ar-SA

google_analytics: UA-XXXXXXXX-X

markdown: kramdown

url: https://el3zahaby.github.io

twitter:
  username: #
  
facebook:
  app_id: #
  
social:
  links:
    - https://twitter.com/--
    - https://www.facebook.com/--
    
logo: /assets/img/logo512.png

gems:
  - jekyll-archives

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled: 
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/
        
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jemoji
