name: 7el |حِل
title: 7el
description: موقع 7el التعليمي لحل الكتب الدراسية عبر منصة تعليمية ينشر الموقع من خلال انشاء فصول دراسية للمرحلة الابتدائية والمتوسطة والثانوية يساهم الموقع في نشر التعليم عبر نشر الكتب الدراسية
author:
  name: 7el™
  uri: //elzahaby.tk
lang: ar-SA
permalink: pretty
google_analytics: UA-XXXXXXXX-X
markdown: kramdown
url: https://el3zahaby.github.io
twitter:
  username: #
facebook:
  app_id: #
social:
  links:
    - https://twitter.com/--
    - https://www.facebook.com/--
logo: /assets/images/h101_angle.png
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jemoji
